#transform_tolerance: 0.05

min_particles: 10
max_particles: 1000
first_map_only: true
resample_interval: 1

update_min_d: 0.05
update_min_a: M_PI/12.0

initial_pose_x: 0
initial_pose_y: 0
initial_pose_a: 0

laser_z_hit: 0.95
laser_z_rand: 0.05

odom_alpha1: 0.01
odom_alpha2: 0.001
odom_alpha3: 0.001
odom_alpha4: 0.001

