map_type: costmap

obstacle_range: 5.0
raytrace_range: 0.5

transform_tolerance: 0.12

footprint: [[-0.2, 0.2], [0.2, 0.2], [0.2, -0.2], [-0.2, -0.2]]
#robot_radius: 0.3 
inflation_radius: 0.4 #0.6

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
